[package]
name = "glucoguard"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio-rustls"] }
tokio = { version = "1", features = ["full"] }
sha2 = "0.10.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }